<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250609172138 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE appointment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, notes VARCHAR(255) DEFAULT NULL, status VARCHAR(20) NOT NULL, price DOUBLE PRECISION NOT NULL, therapist_id INT NOT NULL, client_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_FE38F84443E8B094 ON appointment (therapist_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_FE38F84419EB6921 ON appointment (client_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE availability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_hour INT NOT NULL, end_hour INT NOT NULL, day_of_week INT NOT NULL, is_available BOOLEAN NOT NULL, excluded_date DATE DEFAULT NULL, therapist_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_3FB7A2BF43E8B094 ON availability (therapist_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, hourly_rate DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE appointment ADD CONSTRAINT FK_FE38F84443E8B094 FOREIGN KEY (therapist_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE appointment ADD CONSTRAINT FK_FE38F84419EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE availability ADD CONSTRAINT FK_3FB7A2BF43E8B094 FOREIGN KEY (therapist_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE appointment DROP CONSTRAINT FK_FE38F84443E8B094
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE appointment DROP CONSTRAINT FK_FE38F84419EB6921
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE availability DROP CONSTRAINT FK_3FB7A2BF43E8B094
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE appointment
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE availability
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE "user"
        SQL);
    }
}
